### ISSUE TITLE
customer-side concern

### ISSUE THREAD

**Issue by keatans** [oscarpedrero/BloodyShop#11]
thank you for the speed just a small problem even after having installed UniverseLib.IL2CPP.Interop.dll in client side BepInEx\
plugins impossible to have the possibility of configuring the F11 key (not present in the key menu) it is therefore impossible for me to use the opening menu 
thanks again ;)
![2024-05-26 034131](https://github.com/oscarpedrero/BloodyShop/assets/51285908/56e0f530-4028-4b69-bcd7-ffdacb7f65f2)

**Comment by oscarpedrero** [comment]
![image](https://github.com/oscarpedrero/BloodyShop/assets/6031863/58a89e05-8bd6-46ca-a172-28a29b0bbf6f)
