### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by youyo-Git** [oscarpedrero/BloodyShop#7]
My Chinese client looks like this
![}3T34(6CU $ VB9N92332 0](https://user-images.githubusercontent.com/56459568/202367721-5aea8fa4-a4d1-446e-9d3c-b5fab3e07a99.png)
I switched the game client to English and the name of the store item appeared normally
![_FSXG _SQ7%50{UK(DEN)(G](https://user-images.githubusercontent.com/56459568/202367481-c394c6a8-7c9f-4559-a071-e2f01c4425fb.png)
I wish this mod could support Chinese，thank you！i love this mod.

**Comment by youyo-Git** [comment]
![}3T34(6CU $ VB9N92332 0](https://user-images.githubusercontent.com/56459568/202367721-5aea8fa4-a4d1-446e-9d3c-b5fab3e07a99.png)

**Comment by oscarpedrero** [comment]
It's a problem with how the server returns the names.
