### ISSUE TITLE
Asking for 1.0

### ISSUE THREAD

**Issue by MandoDB** [oscarpedrero/BloodyShop#9]
Do you gonna update your mod for 1.0 ?

**Comment by oscarpedrero** [comment]
Yes, At the moment there is a problem with the client / server messages for the UI and we are working on it, when I have it solved I will launch a pre-release

**Comment by MandoDB** [comment]
Thanks you so much !

**Comment by oscarpedrero** [comment]
https://github.com/oscarpedrero/BloodyShop/releases/tag/v1.0.0
